Repository googleapis/python-documentai, pull requests merged in 2020-06, with the labels that each got.

#25 chore: Migrate python-documentai synth.py from microgenerator docker image to bazel
  synth.py
Labels: cla: yes

#23 chore: add templates for samples
  .coveragerc
  .flake8
  .gitignore
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
Labels: automerge, cla: yes, context: full

#27 fix(python): change autodoc_default_flags to autodoc_default_options
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: full
