Repository googleapis/python-documentai, pull requests merged in 2020-11, with the labels that each got.

#56 chores: fixed small issue with start index problem
  samples/snippets/batch_process_documents_sample_v1beta3.py
  samples/snippets/process_document_sample_v1beta3.py
  samples/snippets/quickstart_sample_v1beta3.py
Labels: api: documentai, automerge, cla: yes

#43 feat: add common resource path helpers, expose client transport
  .kokoro/docs/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  CODE_OF_CONDUCT.md
  docs/conf.py
  docs/documentai_v1beta2/types.rst
  docs/documentai_v1beta3/types.rst
  google/cloud/documentai_v1beta2/services/document_understanding_service/async_client.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/client.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/base.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc_asyncio.py
  google/cloud/documentai_v1beta2/types/geometry.py
  google/cloud/documentai_v1beta3/services/document_processor_service/async_client.py
  google/cloud/documentai_v1beta3/services/document_processor_service/client.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/base.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc_asyncio.py
  google/cloud/documentai_v1beta3/types/geometry.py
  noxfile.py
  scripts/fixup_documentai_v1beta2_keywords.py
  scripts/fixup_documentai_v1beta3_keywords.py
  synth.metadata
  synth.py
  tests/unit/gapic/documentai_v1beta2/test_document_understanding_service.py
  tests/unit/gapic/documentai_v1beta3/test_document_processor_service.py
Labels: cla: yes, context: partial

#58 chore: update samples noxfile
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: documentai, cla: yes, context: none

#59 fix: removes C-style semicolons and slash comments
  samples/snippets/process_document_sample_v1beta3.py
  samples/snippets/quickstart_sample_v1beta3.py
Labels: api: documentai, cla: yes
