Repository googleapis/python-documentai, pull requests merged in 2020-12, with the labels that each got.

#63 fix: added if statement to filter out dir blob files
  samples/snippets/batch_process_documents_sample_v1beta3.py
Labels: api: documentai, automerge, cla: yes

#68 fix: change comments to match function signature
  samples/snippets/batch_process_documents_sample_v1beta3.py
Labels: api: documentai, cla: yes

#71 fix: moves import statement inside region tags
  samples/snippets/process_document_sample_v1beta3.py
Labels: api: documentai, cla: yes

#69 samples: added test that covers the wrong file type case
  samples/snippets/batch_process_documents_sample_bad_input_v1beta3_test.py
  samples/snippets/batch_process_documents_sample_v1beta3.py
Labels: api: documentai, cla: yes, samples

#72 fix: remove client recv msg limit and add enums to `types/__init__.py`
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/__init__.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc_asyncio.py
  google/cloud/documentai_v1beta2/types/__init__.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/__init__.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc_asyncio.py
  google/cloud/documentai_v1beta3/types/__init__.py
  synth.metadata
  tests/unit/gapic/documentai_v1beta2/test_document_understanding_service.py
  tests/unit/gapic/documentai_v1beta3/test_document_processor_service.py
Labels: api: documentai, cla: yes, context: full

#74 chore: update templates
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: documentai, cla: yes, context: full
