Repository googleapis/python-documentai, pull requests merged in 2021-03, with the labels that each got.

#65 chore: require samples checks
  .github/sync-repo-settings.yaml
Labels: api: documentai, cla: yes, samples

#93 fix(samples): swaps 'continue' for 'return'
  samples/snippets/batch_process_documents_sample_v1beta3.py
Labels: api: documentai, cla: yes

#94 fix: adds comment with explicit hostname change
  samples/snippets/batch_process_documents_sample_v1beta3.py
  samples/snippets/process_document_sample_v1beta3.py
  samples/snippets/quickstart_sample_v1beta3.py
Labels: api: documentai, cla: yes

#89 chore: upgrade gapic-generator-python to 0.40.5
  google/cloud/documentai_v1beta2/services/document_understanding_service/client.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc.py
  google/cloud/documentai_v1beta2/services/document_understanding_service/transports/grpc_asyncio.py
  google/cloud/documentai_v1beta3/services/document_processor_service/client.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc.py
  google/cloud/documentai_v1beta3/services/document_processor_service/transports/grpc_asyncio.py
  synth.metadata
  tests/unit/gapic/documentai_v1beta2/test_document_understanding_service.py
  tests/unit/gapic/documentai_v1beta3/test_document_processor_service.py
Labels: api: documentai, cla: yes, context: full

#82 chore: update templates
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: api: documentai, automerge, cla: yes, context: full

#97 chore: update templates
  .github/header-checker-lint.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  CONTRIBUTING.rst
  MANIFEST.in
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: documentai, cla: yes, context: full
